### ISSUE TITLE
Cannot connect - 521 from cloudflare

### ISSUE THREAD

**Issue by LaVolsi** [stayallive/laravel-websockets-example#1]
I installed it with forge and am using a Origin Cert for SSL. 
The 2053 port is open in the firewall
The DNS A record is set pointing to the servers IP. 
The Nginx file has been configured with server section duplicated, configured with 2053 and the location section replaced. 
I am even running 2 instances of the websocket on 6001 and 6003. 

The website loads but I get a 521 error back on the wss connection. 

Googling the error returns "Error 521 occurs because the origin web server refuses a connection from Cloudflare." Is there some setting that I am missing with cloudflare that is preventing the connection from happening? I have verified manually the firewall settings have the 2053 port open and a telnet ping connects on port 2053... Thanks in advance!

**Comment by stayallive** [comment]
Hmm that is weird, all seems fine from what you are saying. The 521 does indicate a connection error between Cloudflare and your server, 2 things come to mind.

Did you leave the IP blank when opening 2053 in the firewall? If not it will only allow connections on that IP.

The next thing that comes to mind is that you are not using a https host. Are you sure there is a (either valid or a CF origin certificate) enabled on your socket domain and both the server blocks in the NGINX config contain something like `listen 2053 ssl # or http2`?

I assume you are running 2 `php artisan websockets:serve` servers and not webservers on 6001 & 6003, just to check :)

**Comment by LaVolsi** [comment]
In my server->network tab on forge
Websockets | 2053 | Any

My modifications on the Nginx file:
copied server and pasted it below the original (443); then
server {
    listen 2053 ssl http2;
    listen [::]:2053 ssl http2;

...

    location / {
        proxy_pass             http://127.0.0.1:6003;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;

        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }


and yes to websocket - sorry typo! lol

**Comment by stayallive** [comment]
In the networking tab in the Cloudflare control panel you can actually disable websockets, it's along shot, but that could be disabled possibly?

Below my full NGINX config that is working right now on my domain, maybe you notice something about it.

<details>
<summary>Click to expand NGINX config</summary>

```
# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/laravel-websockets-example.bouma.me/before/*;

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name laravel-websockets-example.bouma.me;
    root /home/forge/laravel-websockets-example.bouma.me/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/laravel-websockets-example.bouma.me/473597/server.crt;
    ssl_certificate_key /etc/nginx/ssl/laravel-websockets-example.bouma.me/473597/server.key;

    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/laravel-websockets-example.bouma.me/server/*;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/laravel-websockets-example.bouma.me-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 2053 ssl;
    listen [::]:2053 ssl;
    server_name laravel-websockets-example.bouma.me;
    root /home/forge/laravel-websockets-example.bouma.me/public;

    # FORGE SSL (DO NOT REMOVE!)
    ssl_certificate /etc/nginx/ssl/laravel-websockets-example.bouma.me/473597/server.crt;
    ssl_certificate_key /etc/nginx/ssl/laravel-websockets-example.bouma.me/473597/server.key;

    ssl_protocols TLSv1.2;
    ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384;
    ssl_prefer_server_ciphers on;
    ssl_dhparam /etc/nginx/dhparams.pem;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

    index index.html index.htm index.php;

    charset utf-8;

    # FORGE CONFIG (DO NOT REMOVE!)
    include forge-conf/laravel-websockets-example.bouma.me/server/*;

    location / {
        proxy_pass             http://127.0.0.1:6003;
        proxy_read_timeout     60;
        proxy_connect_timeout  60;
        proxy_redirect         off;
        
        # Allow the use of websockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    access_log off;
    error_log  /var/log/nginx/laravel-websockets-example.bouma.me-error.log error;

    error_page 404 /index.php;

    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.1-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

# FORGE CONFIG (DO NOT REMOVE!)
include forge-conf/laravel-websockets-example.bouma.me/after/*;
```
</details>

<br>

Just noticed about my config I do not have http2 enabled... you could try to disable that just to check?

**Comment by LaVolsi** [comment]
Okay so I tried it out and still no luck.. 
I did look around cloudflare a little more and was curious how you have your crypto tab configured?
Are you using Full Strict mode? What about Universal SSL or Edge Certs? 
TLS1.3 enabled? Authenticated Origin Pulls enabled?

**Comment by stayallive** [comment]
This is [my crypto tab](https://f.bouma.me/v/4j7JtGcNBmmI0QMBj7ee).

**Comment by LaVolsi** [comment]
hmm mine is basically the same..
Just noticed cloudflare has a firewall tab... 
Did you allow the websocket through on there?

**Comment by stayallive** [comment]
No that is for traffic to Cloudflare, not the other way around.

Only setting for WebSockets is on the Network tab of the Cloudflare CP.

You can still try to disable the Cloudfare proxy and see what changes, since it should function without the proxy enabled in the first place. If that's not working either something might be wrong on your server. But if it does work it might be worth hitting up Cloudflare support to see what the connection issue is.

**Comment by LaVolsi** [comment]
I got it to work! I'm not sure what the problem was exactly but after giving the server a reboot from a terminal; I came back to the pc and the socket connected... smh. I guess maybe Nginx was not registering my changes/forge reboot commands.. Working great! thanks again :D

**Comment by stayallive** [comment]
Haha, restart when in doubt 👍 Perfect!

**Comment by sparkison** [comment]
I was able to get the websocket server up and running with the guide @stayallive posted, so first, thank you!!

However, looking at Laravel Horizon none of my events are broadcasting. Pulling up the job details they are all showing the following error:

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```

Any idea how to fix/adjust for this?

**Comment by ashokrajc87** [comment]
In SSL/TLS Tab

change encryption mode from Full to Flexible.
