### ISSUE TITLE
The plain HTTP request was sent to HTTPS port

### ISSUE THREAD

**Issue by stayallive** [stayallive/laravel-websockets-example#2]
@sparkison wrote:

> I was able to get the websocket server up and running with the guide @stayallive posted, so first, thank you!!
>
> However, looking at Laravel Horizon none of my events are broadcasting. Pulling up  the job details they are all showing the following error:
>
> ```400 Bad Request
> The plain HTTP request was sent to HTTPS port
> ```
>
> Any idea how to fix/adjust for this?

(From #1 but to prevent notifying that OP with out conversation)

**Comment by stayallive** [comment]
Hey @sparkison,

It sounds like Laravel is trying to connect to you API via the internet instead of via `127.0.0.1`.

Do you have anything different than this in your `config/broadcasting.php`?

https://github.com/stayallive/laravel-websockets-example/blob/master/config/broadcasting.php#L41-L42

Laravel _should_ talk over HTTP to your websockets server. But if you are using the internet facing port (configured in NGINX) or the hostname your clients use it will not work and because of the forced HTTPS redirect complain about a HTTP request to a HTTPS port.

So make sure to keep the port you are running `php artisan websockets:serve` different from the port you configure in nginx as external port.

For example in this post https://alex.bouma.dev/installing-laravel-websockets-on-forge/:
We use port `6001` (the default) for `php artisan websockets:serve`) and Laravel connects to `127.0.0.1:6001`. But the clients (your apps' users) connect to `domain.tld:6002`.

**Comment by sparkison** [comment]
Hey @stayallive,

I posted a comment in another issue that seemed more appropriate: [https://github.com/beyondcode/laravel-websockets/issues/99#issuecomment-469473922](https://github.com/beyondcode/laravel-websockets/issues/99#issuecomment-469473922)

But to answer your question, I am using 127.0.0.1 in `broadcasting.php`. And I setup the server block like you have on the blog post mentioned.

Here's some more detail for you...

The failed jobs all have the following: 
```
Illuminate\Broadcasting\BroadcastException:
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx/1.15.8
in /home/forge/tld.com/vendor/laravel/framework/src/Illuminate/Broadcasting/Broadcasters/PusherBroadcaster.php:117
Stack trace:
#0 /home/forge/tld.com/vendor/laravel/framework/src/Illuminate/Broadcasting/BroadcastEvent.php(48): Illuminate\Broadcasting\Broadcasters\PusherBroadcaster->broadcast(Array, 'App\\Events\\Task...', Array)
...
```

Using Forge with HTTPS and the proxy recommended setup from here: [https://alex.bouma.dev/installing-laravel-websockets-on-forge](https://alex.bouma.dev/installing-laravel-websockets-on-forge)

My pusher connection is as follows:
```
...
'pusher' => [
            'driver' => 'pusher',
            'key' => env('PUSHER_APP_KEY'),
            'secret' => env('PUSHER_APP_SECRET'),
            'app_id' => env('PUSHER_APP_ID'),
            'options' => [
                'cluster' => env('PUSHER_APP_CLUSTER'),
                'encrypted' => env('WS_ENCRYPTED' ,true),
                'host' => env('WS_HOST' ,'127.0.0.1'),
                'port' => env('WS_PORT', 6002),
                'scheme' =>  env('WS_SCHEME', 'http')
            ],
        ],
...
```

And .env
```
...
PUSHER_APP_ID=ldhgljdhjh
PUSHER_APP_KEY=kdgjhdkjhdjghkjdhgkjdfhgkjdh
PUSHER_APP_SECRET=kkrjhwejkhjnkjdkjgdfg
PUSHER_APP_CLUSTER=default

WS_HOST=127.0.0.1
WS_PORT=6002
WS_SCHEME=http
WS_ENCRYPTED=false
WS_SSL_CERT=
WS_SSL_KEY=
...
```

I also tried this recommendation: [https://serverfault.com/a/664936](https://serverfault.com/a/664936) but that just changes the error to 
```
Illuminate\Broadcasting\BroadcastException:
307 Temporary Redirect
```

**Comment by stayallive** [comment]
You are still getting an error message from nginx... you are talking to the wrong port! Laravel should talk _directly_ to `php artisan websockets:serve` not the port you configure nginx to listen on.

> For example in this post https://alex.bouma.dev/installing-laravel-websockets-on-forge/:
> We use port 6001 (the default) for php artisan websockets:serve) and Laravel connects to 127.0.0.1:6001. But the clients (your apps' users) connect to domain.tld:6002.

Hope that explains it 👍

**Comment by sparkison** [comment]
> You are still getting an error message from nginx... you are talking to the wrong port! Laravel should talk _directly_ to `php artisan websockets:serve` not the port you configure nginx to listen on.
> 
> > For example in this post https://alex.bouma.dev/installing-laravel-websockets-on-forge/:
> > We use port 6001 (the default) for php artisan websockets:serve) and Laravel connects to 127.0.0.1:6001. But the clients (your apps' users) connect to domain.tld:6002.
> 
> Hope that explains it 👍

Gotcha!! Sorry, that wasn't clicking until just now 😜 
I'll give that a shot, guessing that's the ticket though.

Thanks again @stayallive!!

**Comment by stayallive** [comment]
No problem, if that solved it feel free to close the issue 👍

**Comment by sparkison** [comment]
That was indeed the issue, and is now solved.
